### PR TITLE
fixed avatar spacing

### PR DESCRIPTION
**Pull request by godwin-morwin**
still finding it hard to run the background in other to make the avatar visible for clarification, but i still made some changes in the area which I know the problem might be coming from.

### CODE REVIEW

**Review by vighnesh192 — COMMENTED** [review]
Hi @Godwindaniel10, unfortunately the changes doesn't help. Actually, it has nothing to do with flex.
I just found a hack for you which shows an avatar without having to setup the backend:-
You can go to Local Storage of the Application and add `User` as a key and `""` (empty string) as its value, refresh the page and it will show a default Avatar.
Thank You!

**Comment by JorawarSingh12** [comment]
Hi, @vighnesh192 I was setting up the repo, I did the Local Storage hack and it worked. However, when I am trying to post-project it is not working( I haven't set up the backend for the project).  Is there some hack for it or should I set up the backend?

**Comment by vighnesh192** [comment]
> Hi, @vighnesh192 I was setting up the repo, I did the Local Storage hack and it worked. However, when I am trying to post-project it is not working( I haven't set up the backend for the project). Is there some hack for it or should I set up the backend?

Hi @JorawarSingh12! The localStorage hack would only work for the avatar. You'll have to set the backend up for any other functionality to work.

**Comment by ehteshaxm** [comment]
@vighnesh192 Thanks for the help, will this work?
Screenshot (261)

**Comment by vighnesh192** [comment]
> @vighnesh192 Thanks for the help, will this work?
> Screenshot (261)

This is nearly perfect. I think it's very few pixels away from being inline with Top Creators card.

**Comment by ehteshaxm** [comment]
Screenshot (267)

It is at the edge of the line, that's the most it can go I think.

**Comment by vighnesh192** [comment]
Ohh okay. So, that little space might be there because of the default avatar. My bad!
This works, thank you! @cadmaus

**Comment by ehteshaxm** [comment]
@vighnesh192 , Happy to help :)

**Comment by vighnesh192** [comment]
You can create a PR so that I can merge the changes you've made @cadmaus

**Comment by ehteshaxm** [comment]
@vighnesh192 Ok

**Pull request closed without merging**
